# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
